import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { AuthProvider } from "@/context/AuthContext"; // ✅ Import Auth Context
import './styles/footer.css';
import './globals.css';

import RouteGuard from '@/components/RouteGuard';
import JotaiProvider from '@/components/JotaiProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
            <JotaiProvider>
              <RouteGuard>
                <AuthProvider> 
                  <Navbar />
                    {children}
                  <Footer />
                </AuthProvider>
              </RouteGuard>
            </JotaiProvider>
      </body>
    </html>
  );
}
