import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { AuthProvider } from "@/context/AuthContext"; // ✅ Import Auth Context
import './styles/navbar.css';
import './styles/footer.css';
import './globals.css';

import Providers from '@/components/Providers';
import RouteGuard from '@/components/RouteGuard';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body  suppressHydrationWarning>
        <AuthProvider>
          <Providers>
            <RouteGuard>
              <Navbar /> 
              {children}
              <Footer />
            </RouteGuard>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
